sonar.projectKey=corgicorner_bisibility-sdk-go
sonar.projectName=bisibility-sdk-go
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,coverage.out,bin/**,graphify-out/**
sonar.cpd.exclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
